services:
  db:
    image: mariadb:11.4
    container_name: mini-anime-list-db
    environment:
      MARIADB_ROOT_PASSWORD: sapassword
      MARIADB_DATABASE: animelist
    ports:
      - "3307:3306"
    volumes:
      - mini_anime_list_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: mini-anime-list-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/animelist
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sapassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: mini-anime-list-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mini_anime_list_db_data: